route:
  receiver: email-me
  repeat_interval: 3h #3h
  group_interval: 5m #5m
  group_wait: 1m #1m

receivers:
- name: 'email-me'
  email_configs:
  - to: 'user_to@mail.com' 
    from: 'user_from@mail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'user_from@mail.com'
    auth_identity: 'user_from@mail.com'
    auth_password: 'FromPassword'
