version: '3.2'

volumes:
  vol-prometheus-data: {}
  vol-grafana-data: {}

networks:
  net-monitor:
    driver: overlay 

services:
  prometheus:
    image: cm/cm-prometheus
    volumes:
      - ./prometheus/config/:/etc/prometheus/
      - vol-prometheus-data:/prometheus
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    networks:
      - net-monitor
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  node-exporter:
    image: cm/cm-node-exporter
    hostname: '{{.Node.ID}}'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - net-monitor
    deploy:
      mode: global
  cadvisor:
    image: cm/cm-cadvisor 
    hostname: '{{.Node.ID}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - net-monitor
    deploy:
      mode: global
  grafana:
    image: cm/cm-grafana
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - vol-grafana-data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/etc/grafana/custom_dashboards
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - net-monitor
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
